// <auto-generated />
using System;
using BE_Drink.DbContext;
using BE_Drink.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BE_Drink.Migrations
{
    [DbContext(typeof(BE_DrinkContext))]
    [Migration("20210912170313_full_product")]
    partial class full_product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BE_Drink.Models.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("availability")
                        .HasColumnType("int");

                    b.Property<string>("banner_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("cover_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("desciption")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("price")
                        .HasColumnType("money");

                    b.Property<int>("returned")
                        .HasColumnType("int");

                    b.Property<decimal>("revenue")
                        .HasColumnType("money");

                    b.Property<decimal>("sale")
                        .HasColumnType("money");

                    b.Property<string>("seller_id")
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("storage_instructions")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("unit")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("view")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
